import Head from 'next/head'
import Link from 'next/link'
import dynamic from 'next/dynamic'
import { GetServerSidePropsContext, NextPage } from 'next'
import styled from '@emotion/styled'
import { GlassmorphismStyle } from '@/components/Glassmorphism'
import { BudouJa } from '@/utils/wrapper/BudouX'
import { HiArrowRight } from 'react-icons/hi'
import { useCallback, useEffect, useState } from 'react'
import { lightTheme } from '@/utils/theme/default'
import { Logo } from './components/Logo'
import { useThemeList } from '@/utils/theme/hooks'
import { resolveTheme } from '@/utils/theme'
import { SmallPreview } from '@/components/preview'
import { extractShowcaseUser } from '@/utils/extractUser'
import { css } from '@emotion/react'
import { useRouter } from 'next/router'
import { TrimMark, TrimMarkGroup } from './components/TrimMark'
import { isMobile, useIsMobile } from '@/utils/isMobile'

const Fluid = dynamic(
  () => import('@/components/Fluid.client').then(mod => mod.Fluid),
  {
    ssr: false,
  }
)

export const getServerSideProps = async ({
  req,
}: GetServerSidePropsContext) => {
  const userId = extractShowcaseUser(req)

  // 部員とわかってる人はトップページを表示しない
  // if (userId !== null) {
  //   return {
  //     redirect: {
  //       destination: '/random',
  //       permanent: false,
  //     },
  //   }
  // }

  return {
    props: {},
  }
}

const Home: NextPage = () => {
  const [isShowTopPage, setIsShowTopPage] = useState(true)
  const [isRendered, setIsRendered] = useState(false)

  const router = useRouter()
  useEffect(() => {
    if (localStorage.getItem('isShowTopPage') === '0') {
      void router.replace('/random')
      return
    }
    setIsRendered(true)
  }, [router])

  const onToggleShowTopPage = useCallback(() => {
    setIsShowTopPage(prev => !prev)
    localStorage.setItem('isShowTopPage', isShowTopPage ? '0' : '1')
  }, [isShowTopPage, setIsShowTopPage])

  const { themes } = useThemeList(null, 'public', null, 10)

  const [loginUrl, setLoginUrl] = useState('')
  useEffect(() => {
    setLoginUrl(
      `https://portal.trap.jp/pipeline?redirect=${window?.location.href ?? ''}`
    )
  }, [])

  const isMobile = useIsMobile()

  return (
    <>
      <Head>
        <title>QTheme v2</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <TopContainer hidden={!isRendered}>
        <FluidBackground />
        <TopContentWrap>
          <TrimMarkGroup size={32} margin={isMobile ? 16 : 32} />

          <Title>
            <Logo role='img' aria-label='Qtheme v2' />
          </Title>
          <Description>
            <p>
              <BudouJa>
                Qtheme は traQ のテーマを作成・共有できるサービスです。
              </BudouJa>
            </p>
          </Description>
          <ViewLink href='/random'>
            <span>テーマを見てみる</span>
            <HiArrowRight />
          </ViewLink>

          <LoginButton href={loginUrl}>
            すでに部員の方はこちら
            <HiArrowRight />
          </LoginButton>

          <HorizonWrap>
            {themes.map(theme => {
              const resolvedTheme = resolveTheme(theme.theme)
              return (
                <Card key={theme.id} href={`/theme/${theme.id}`}>
                  <SmallPreview theme={resolvedTheme} author={theme.author} />
                </Card>
              )
            })}
            <Overlay />
          </HorizonWrap>

          <Label>
            <Checkbox
              type='checkbox'
              checked={!isShowTopPage}
              onChange={onToggleShowTopPage}
            />
            <span>このページを今後表示しない</span>
          </Label>
        </TopContentWrap>
      </TopContainer>
    </>
  )
}
export default Home

const TopContainer = styled.main`
  width: 100vw;
  height: 100vh;
  position: relative;
  display: grid;
  place-items: center;

  &[hidden] {
    display: none;
  }
`
const FluidBackground = styled(Fluid)`
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
`

const TopContentWrap = styled.div`
  position: relative;
  z-index: 1;
  width: 100%;
  height: 100%;
  pointer-events: none;
  display: flex;
  flex-direction: column;
  overflow-x: hidden;
  padding: 80px;

  ${isMobile} {
    padding: 48px;
  }
`
const TopContent = styled.div`
  ${GlassmorphismStyle}
  border-radius: 8px;
  padding: 24px;
  display: flex;
  flex-direction: column;

  pointer-events: none;
`
const Title = styled.h1`
  font-size: 3rem;
  margin: 8px 0;

  max-width: 100%;

  svg {
    width: 100%;
    height: auto;
  }

  backdrop-filter: blur(20px);
  background-color: ${lightTheme.basic.accent.primary}33;
  margin-right: auto;
  padding: 24px 16px;
  border-radius: 8px;
`
const Description = styled.div`
  margin: 4px 0;
`

const LinkButtonStyle = css`
  display: flex;
  pointer-events: auto;
  ${GlassmorphismStyle}
  border-radius: 8px;
  padding: 12px 16px;
  align-items: center;
  vertical-align: middle;
  gap: 4px;
  line-height: 1;
  margin: 8px 0;
  margin-right: auto;

  & > svg {
    transition: all 0.2s ease-out;
  }
  &:hover > svg {
    transform: translateX(4px);
  }
`
const ViewLink = styled(Link)`
  ${LinkButtonStyle}
`
const LoginButton = styled.a`
  ${LinkButtonStyle}
`

const Checkbox = styled.input`
  width: 24px;
  height: 24px;
  appearance: auto;

  &:focus {
    outline: 2px solid ${lightTheme.basic.accent.primary};
  }
`
const Label = styled.label`
  display: flex;
  user-select: none;
  cursor: pointer;
  align-items: center;
  margin: 4px 0;
  margin-right: auto;
  pointer-events: auto;
  margin-top: auto;
`

const HorizonWrap = styled.div`
  display: flex;
  flex-direction: row;
  /* overflow: hidden; */
  gap: 8px;
  position: relative;
  width: calc(100% + 80px);
  ${isMobile} {
    width: calc(100% + 48px);
  }
`
const Card = styled(Link)`
  ${GlassmorphismStyle}
  border-radius: 8px;
  padding: 8px;
  display: grid;
  place-items: center;
  min-width: 240px;
  width: 30vw;
  & > * {
    width: 100%;
  }
  pointer-events: auto;
  flex-shrink: 0;
`
const Overlay = styled.div`
  position: absolute;
  pointer-events: none;
  top: 0;
  right: 0;
  bottom: 0;
  max-width: 50%;
  width: 160px;
  background: linear-gradient(
    to right,
    transparent 0%,
    rgba(255, 255, 255) 100%
  );
`
