name: main
on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:

env:
  GITEA_SSH_URL: 'ssh://git@git.trap.jp:2200/SSlime/Qtheme_v2.git'
  PNPM_VERSION: 8

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            **/*.generated.ts
            **/generated
          key: node_modules-generated-${{ github.sha }}
      - run: pnpm install

  type-check:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            **/*.generated.ts
            **/generated
          key: node_modules-generated-${{ github.sha }}
      - run: |
          echo '/// <reference types="next" />' > ./next-env.d.ts
          echo '/// <reference types="next/image-types/global" />' >> ./next-env.d.ts
      - run: pnpm run type-check

  notify-deploy:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: type-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/github-script@v6
        id: generate
        with:
          result-encoding: string
          script: |
            const notifyDeploy = require('${{ github.workspace }}/bin/notify_deploy.cjs')
            return notifyDeploy('${{ github.server_url }}/${{ github.repository }}')
      - uses: SSlime-s/traq-webhook@v4.15
        with:
          webhook-id: ${{ secrets.TRAQ_WEBHOOK_ID }}
          webhook-secret: ${{ secrets.TRAQ_WEBHOOK_TOKEN }}
          message: ${{ steps.generate.outputs.result }}

  deploy:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: type-check
    runs-on: ubuntu-latest
    concurrency:
      group: for-prod-${{ github.workflow }}
      cancel-in-progress: true
    env:
      BRANCH_NAME: tmp-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - run: git switch -c ${{ env.BRANCH_NAME }}
      - name: Set Config
        run: |
          echo "${{ secrets.GITEA_TOKEN }}" > ~/deploy_key.pem
          chmod 600 ~/deploy_key.pem
          git config --local user.email "github@actions"
          git config --local user.name "github"
      - name: Push
        env:
          GIT_SSH_COMMAND: ssh -i ~/deploy_key.pem -o StrictHostKeyChecking=no -F /dev/null
        run: |
          git fetch --unshallow origin
          git push -f -u ${{ env.GITEA_SSH_URL }} ${{ env.BRANCH_NAME }}:master
